#!/bin/bash --login

#PBS -N pbs-py-fssh
#PBS -l select=serial=true:ncpus=24
#PBS -l walltime=00:30:00
#PBS -A e05-softm-blu

module load anaconda
source activate forgenerator

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

python bin/run-adiabatic-couplings.py ARCHER 24
